### PR TITLE
refact(der-to-jose) add additional param length checks

### PR DESCRIPTION
**Pull request by omsmith**

### CODE REVIEW

**Comment by omsmith** [comment]
@j3parker When you have a minute, no real rush as its not particularly important. Suggested reading with [?w=1](https://github.com/Brightspace/node-ecdsa-sig-formatter/pull/13?w=1)

Just adds an additional sanity/correctness check when reading in a DER signature.

The DER representation, a minimally represented signed integer, should be at most `paramLength + 1`, given they could be the full length with a leading zero when necessary to disambiguate positivity. Using the "happy path fuzzing", this is usually the case.

**Comment by j3parker** [comment]
Whoops! Will look tomorrow

**Comment by j3parker** [comment]
Haha I forgot about the leading zero for positivity thing. Sigh.

:shipit: but you're the expert :)

Is the sanity check just for helping lawful-good devs or is it also a perf thing?

**Comment by omsmith** [comment]
Eh, would just be to avoid following through the whole process, allocating buffers and copying and whatnot if it couldn't possibly be valid

**Comment by j3parker** [comment]
Sounds reasonable. Better to reject crap data early.

**Pull request merged**
